services:
  pandas:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ..:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python mle-assignment/main.py --start 2023-05-01 --end 2023-11-01
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ..:/app
    environment:
      - PYTHONUNBUFFERED=1
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-arm64
    command: python mle-assignment/spark_main.py --start 2023-05-01 --end 2023-11-01